In [31]:
# ==========================================
# Notebook 04
# Item Embedding Generator
# ==========================================

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer

In [32]:
profiles_df = pd.read_csv("../data/item_profiles.csv")

profiles_df.head()

,item_id,title,category,tags,content_profile
0,1,The Early Days of Stripe,Startup,startup fintech founders entrepreneurship vent...,Title: The Early Days of Stripe Category: Star...
1,2,Building SpaceX,Startup,startup fintech founders entrepreneurship vent...,Title: Building SpaceX Category: Startup Tags:...
2,3,AI for Healthcare,Artificial Intelligence,ai machine-learning llm deep-learning transfor...,Title: AI for Healthcare Category: Artificial ...
3,4,The Psychology of Habits,Wellness,habits productivity self-improvement,Title: The Psychology of Habits Category: Well...
4,5,Cloud Computing Fundamentals,Technology,cloud computing distributed-systems scalability,Title: Cloud Computing Fundamentals Category: ...

In [33]:
print("Total Profiles:", len(profiles_df))

print()

profiles_df.columns

Total Profiles: 10

Index(['item_id', 'title', 'category', 'tags', 'content_profile'], dtype='object')

In [34]:
embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [35]:
embedding_model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [36]:
documents = profiles_df["content_profile"].tolist()

In [37]:
len(documents)

10

In [38]:
documents[0]

"Title: The Early Days of Stripe Category: Startup Tags: startup fintech founders entrepreneurship venture-capital Description: \n        Story of how Stripe scaled into\n        one of the world's largest\n        fintech companies.\n        "

In [39]:
item_embeddings = embedding_model.encode(documents, show_progress_bar=True)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [40]:
item_embeddings.shape

(10, 384)

In [41]:
item_embeddings[0]

array([-2.13364158e-02,  1.58938149e-03, -5.13304211e-02, -2.97792517e-02,
       -6.60088519e-03, -1.55283250e-02,  4.08354737e-02,  5.16616590e-02,
       -3.39248516e-02, -1.50033319e-02, -1.02398349e-02,  2.82043610e-02,
       -3.83497365e-02,  9.01229307e-02, -2.39704512e-02, -2.84749009e-02,
       -1.04348548e-02, -5.19594029e-02,  3.05004697e-02,  3.37638296e-02,
       -4.49055471e-02, -8.00923258e-02,  1.04316426e-02,  5.39698564e-02,
        6.75261766e-02,  4.06304002e-02,  7.26671470e-03,  2.56847125e-04,
       -5.50831743e-02, -1.07916445e-01, -3.29991281e-02,  7.41584674e-02,
        5.67254126e-02,  1.07447077e-02,  4.00880910e-02, -4.81372932e-03,
        1.62653793e-02, -3.01518701e-02, -3.61125846e-03, -4.47111130e-02,
        1.03005104e-01, -5.82102090e-02, -3.43533196e-02,  1.58608425e-02,
        5.19482791e-02, -7.05559552e-02, -1.17440745e-02,  6.94275601e-03,
       -1.04182921e-02,  5.57733774e-02,  3.55312377e-02, -1.22866936e-01,
        5.83510436e-02, -1.05884764e-02, -1.81375276e-02, -1.50398761e-02,
       -8.28695484e-03, -3.17855999e-02,  7.72868767e-02, -4.42803502e-02,
        2.51994114e-02,  1.61258262e-02,  5.44164255e-02,  6.56971633e-02,
       -2.70187613e-02,  3.83146852e-02, -2.86915936e-02,  8.44522789e-02,
       -5.18565290e-02, -2.27651675e-03,  3.83240245e-02, -3.95242050e-02,
       -3.57925966e-02,  8.54963362e-02,  2.08621230e-02, -4.29529101e-02,
        4.18546610e-02,  1.22782663e-01,  5.42311091e-03, -4.68602367e-02,
       -9.63739604e-02, -3.58864181e-02, -5.75342067e-02,  5.35462871e-02,
       -1.08252548e-01,  4.12643999e-02, -1.28340526e-02, -4.30399738e-02,
        3.23939808e-02, -5.52739166e-02, -2.62883641e-02,  1.14607744e-01,
        5.21231107e-02, -2.85162479e-02, -6.84885755e-02, -6.68600127e-02,
       -1.08831249e-01, -1.03335708e-01, -2.85964110e-03,  2.22224332e-02,
        7.43594468e-02,  7.43726417e-02,  5.81278512e-03,  6.91426247e-02,
        7.58545920e-02, -1.45647004e-02,  3.64665613e-02,  6.17307238e-02,
        5.74684814e-02, -1.37592144e-02,  1.84496550e-03, -3.16716381e-03,
        2.86068860e-02, -2.84439139e-02, -1.17780250e-02, -4.58876155e-02,
       -7.04688504e-02,  5.28044365e-02,  9.81531367e-02,  1.17114037e-01,
        2.04618219e-02,  8.85260701e-02, -4.65459041e-02, -1.38796851e-01,
       -6.38280809e-02,  4.95191887e-02, -8.32037628e-03, -1.32577359e-33,
        2.23771352e-02,  4.14914228e-02,  3.41487229e-02,  4.43859510e-02,
        2.06421670e-02, -2.30137091e-02, -8.61126091e-03,  5.81847690e-02,
       -1.23393238e-01,  1.52355684e-02,  2.11695489e-02, -4.36432958e-02,
       -3.83550599e-02,  1.02945015e-01, -1.50820827e-02, -4.71639819e-02,
        1.63634811e-02, -2.00052392e-02,  1.20838573e-02,  1.33605571e-02,
       -4.11273837e-02, -1.28545715e-02,  2.96194348e-02, -7.67266192e-03,
        2.33680792e-02, -5.57144657e-02, -8.91599208e-02,  1.52580049e-02,
        6.06551059e-02,  5.98304942e-02,  1.23262443e-02, -2.01978888e-02,
        5.51396608e-02, -7.09299296e-02, -5.26309796e-02,  3.30788083e-02,
        7.57200196e-02, -7.15604499e-02,  1.42581193e-02, -1.30664064e-02,
        2.25200709e-02, -1.22419922e-02,  9.06204432e-03, -7.81291872e-02,
       -3.07311714e-02,  8.36656690e-02,  7.18225762e-02, -3.70311253e-02,
        1.17294215e-01,  1.51155312e-02, -7.47453049e-02, -1.63957644e-02,
        1.50302388e-02, -1.14555350e-02, -2.12664381e-02, -1.27635030e-02,
       -5.97132146e-02, -6.17527217e-02, -6.49846271e-02, -6.58458620e-02,
       -7.18950853e-02, -2.79733948e-02, -8.45988169e-02,  7.22238347e-02,
       -5.83684593e-02, -2.13593319e-02,  1.32982388e-01,  1.38118854e-02,
       -3.34102698e-02,  8.08177050e-03, -3.52786481e-02, -9.21350997e-03,
       -3.87522578e-02,  2.45983619e-02,  1.68799628e-02,  1.61739495e-02,
       -7.39157125e-02,  2.50513591e-02,  1.02049662e-02,  6.15784861e-02,
       -6.65924847e-02, -8.42915624e-02, -1.77712757e-02, -6.24673031e-02,
       -1.87321622e-02,  8.11740309e-02,  1.73715830e-01, -1.02078468e-01,
       -1.35012548e-02,  3.13642323e-02, -1.16866916e-01,  7.52601996e-02,
        4.37548803e-03,  3.88063267e-02,  1.74788795e-02, -1.81615971e-33,
        3.80304940e-02,  3.13989935e-03,  6.55429214e-02, -1.39736515e-02,
        1.84579007e-02, -3.88666540e-02,  8.66110902e-03,  1.39053902e-02,
       -1.29945092e-02,  6.38493225e-02, -3.53937894e-02,  5.16677424e-02,
       -7.23011792e-02,  9.32169147e-04,  7.11499574e-03, -3.78718115e-02,
       -1.22764269e-02,  3.82418148e-02,  9.29294080e-02,  1.36734387e-02,
        1.93723720e-02, -3.99144888e-02, -2.09423639e-02,  4.95904908e-02,
        5.51821813e-02,  2.60268338e-02,  1.45002520e-02,  5.90594262e-02,
       -4.19703722e-02,  2.32113581e-02, -3.76966409e-02,  4.60818410e-03,
        1.06409909e-02,  3.27527560e-02, -5.04151769e-02, -4.39322740e-03,
       -1.97460521e-02, -8.39167833e-03,  2.82356832e-02, -5.33524789e-02,
       -1.99552346e-02, -3.86755913e-02, -3.76717187e-02, -8.86239335e-02,
       -4.91026975e-02, -1.00602828e-01,  2.04210598e-02,  6.87043145e-02,
       -4.62734476e-02,  7.91403651e-03, -7.62396976e-02,  7.92707428e-02,
        2.77400501e-02,  7.20615089e-02, -6.32395372e-02,  1.68050416e-02,
        1.98242050e-02,  8.67355093e-02, -7.92718604e-02,  3.82780321e-02,
        5.11816703e-03,  5.48850149e-02,  2.25122496e-02, -7.76726753e-04,
        2.66967695e-02, -6.70812950e-02,  2.59595141e-02,  2.86150444e-02,
       -7.78521374e-02, -4.34617624e-02, -2.99225515e-03,  3.68098007e-03,
       -2.23613549e-02, -1.12201339e-02, -1.44066617e-01, -4.77229953e-02,
       -3.76204401e-02, -8.56495500e-02, -2.51360815e-02, -5.87388016e-02,
        4.10275422e-02, -6.20983262e-03, -1.08168588e-03,  9.24155787e-02,
        1.73974986e-04, -2.36207098e-02,  6.61370754e-02, -3.87185775e-02,
        1.56312305e-02,  3.37819606e-02, -8.76678154e-02, -8.23589712e-02,
       -2.73283832e-02,  5.88270836e-02, -1.01216473e-01, -2.95906695e-08,
       -5.07211313e-02,  1.48400012e-02, -4.90383953e-02,  7.52105862e-02,
        3.12084239e-02, -5.69067430e-03, -2.87399106e-02, -3.00584305e-02,
       -2.15106588e-02,  6.06743321e-02, -1.52785648e-02,  2.28419788e-02,
       -5.68650365e-02,  3.09356041e-02,  1.95474587e-02, -4.71571162e-02,
        7.93728326e-03,  8.75341985e-03, -1.93534847e-02,  2.68521365e-02,
        3.28785065e-03,  6.68506697e-02, -1.43937245e-02, -8.70669782e-02,
       -2.95201577e-02, -8.36931914e-03, -2.98439562e-02,  3.00848652e-02,
        3.29981633e-02,  7.02122413e-03,  4.47786301e-02,  4.53448892e-02,
        5.71243651e-02,  2.14653704e-02,  5.19323684e-02,  1.12716958e-03,
       -1.48050385e-02, -6.75734924e-03,  2.60282550e-02,  1.70353856e-02,
        2.39762962e-02, -1.87513493e-02,  2.95890048e-02, -3.20664868e-02,
       -8.62479433e-02, -3.99039276e-02, -6.74182400e-02,  8.72363672e-02,
        1.33316042e-02, -7.26210773e-02,  7.48493988e-03,  1.31825665e-02,
       -6.26631500e-03,  3.66894491e-02,  1.13163935e-02, -1.88623164e-02,
        6.96284603e-03,  3.84622067e-02, -1.71332806e-02,  3.79245095e-02,
        1.20516889e-01, -5.68637773e-02,  7.55048394e-02, -1.79330688e-02],
      dtype=float32)

In [42]:
len(item_embeddings[0])

384

In [43]:
embedding_df = pd.DataFrame(item_embeddings)

embedding_df.head()

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.021336,0.001589,-0.051330,-0.029779,-0.006601,-0.015528,0.040835,0.051662,-0.033925,-0.015003,...,0.011316,-0.018862,0.006963,0.038462,-0.017133,0.037925,0.120517,-0.056864,0.075505,-0.017933
1,0.027306,-0.047626,0.016753,-0.061527,-0.021008,-0.032888,0.060912,0.015195,-0.045884,-0.027095,...,0.018612,0.039884,-0.038688,0.084618,0.010697,-0.029886,0.074290,-0.029545,0.028936,0.027559
2,-0.078346,-0.004525,0.003929,-0.066090,0.005532,-0.042065,-0.010277,0.042649,-0.051656,-0.066911,...,0.051748,0.059906,0.077221,-0.086342,0.003354,0.104092,0.037527,0.044017,-0.044965,-0.021307
3,0.068490,0.005979,-0.040110,0.064891,-0.051967,-0.014224,0.062593,0.006003,-0.071438,-0.021358,...,-0.024052,0.011927,0.051691,0.012610,-0.052049,-0.050758,0.143781,0.028030,-0.015431,-0.014873
4,0.018681,0.029413,-0.065553,-0.074235,0.032086,-0.043718,0.017604,0.014345,-0.037435,0.057680,...,0.035586,-0.028311,0.017458,-0.045064,0.122665,0.085353,0.058242,0.034240,0.009545,0.059948

In [44]:
embedding_df.insert(0, "item_id", profiles_df["item_id"])

In [45]:
embedding_df.head()

,item_id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
0,1,-0.021336,0.001589,-0.051330,-0.029779,-0.006601,-0.015528,0.040835,0.051662,-0.033925,...,0.011316,-0.018862,0.006963,0.038462,-0.017133,0.037925,0.120517,-0.056864,0.075505,-0.017933
1,2,0.027306,-0.047626,0.016753,-0.061527,-0.021008,-0.032888,0.060912,0.015195,-0.045884,...,0.018612,0.039884,-0.038688,0.084618,0.010697,-0.029886,0.074290,-0.029545,0.028936,0.027559
2,3,-0.078346,-0.004525,0.003929,-0.066090,0.005532,-0.042065,-0.010277,0.042649,-0.051656,...,0.051748,0.059906,0.077221,-0.086342,0.003354,0.104092,0.037527,0.044017,-0.044965,-0.021307
3,4,0.068490,0.005979,-0.040110,0.064891,-0.051967,-0.014224,0.062593,0.006003,-0.071438,...,-0.024052,0.011927,0.051691,0.012610,-0.052049,-0.050758,0.143781,0.028030,-0.015431,-0.014873
4,5,0.018681,0.029413,-0.065553,-0.074235,0.032086,-0.043718,0.017604,0.014345,-0.037435,...,0.035586,-0.028311,0.017458,-0.045064,0.122665,0.085353,0.058242,0.034240,0.009545,0.059948

In [46]:
embedding_df.isnull().sum().sum()

0

In [47]:
embedding_df.describe()

,item_id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,5.50000,-0.009853,-0.006273,-0.025165,-0.017841,0.008254,-0.042905,0.011319,0.017810,-0.057137,...,0.022463,0.025335,0.020524,-0.008694,0.014390,0.013380,0.091157,0.016215,0.010402,0.005241
std,3.02765,0.050377,0.029727,0.039911,0.055487,0.037936,0.041377,0.035658,0.022623,0.026783,...,0.037266,0.030859,0.032015,0.056779,0.051204,0.058338,0.038049,0.042383,0.037232,0.025935
min,1.00000,-0.078346,-0.053915,-0.072981,-0.074235,-0.051967,-0.151249,-0.034299,-0.007948,-0.122550,...,-0.051090,-0.028311,-0.038688,-0.086342,-0.052049,-0.050758,0.037527,-0.056864,-0.044965,-0.021307
25%,3.25000,-0.051291,-0.028740,-0.048525,-0.060565,-0.017406,-0.043526,-0.021528,0.000674,-0.062738,...,0.013140,0.014321,0.006963,-0.044491,-0.015500,-0.034015,0.061118,-0.013285,-0.019299,-0.014011
50%,5.50000,-0.006548,0.002412,-0.035769,-0.033599,0.004259,-0.037477,0.014427,0.010445,-0.053591,...,0.027315,0.028314,0.019818,-0.018626,-0.002736,0.004763,0.083475,0.026361,0.011094,-0.002458
75%,7.75000,0.025149,0.011586,-0.003895,0.029078,0.038212,-0.017362,0.035028,0.035786,-0.039547,...,0.047708,0.042040,0.038243,0.031999,0.045684,0.051689,0.120011,0.041573,0.028258,0.022370
max,10.00000,0.068490,0.029413,0.056544,0.064891,0.064067,-0.005828,0.062593,0.052042,-0.028310,...,0.074591,0.067917,0.077221,0.084618,0.122665,0.104092,0.143781,0.081593,0.075505,0.059948

In [48]:
item_a = item_embeddings[0]

item_b = item_embeddings[1]

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity = cosine_similarity(item_a.reshape(1, -1), item_b.reshape(1, -1))[0][0]

similarity

0.6049122

In [51]:
similarity_matrix = cosine_similarity(item_embeddings)

similarity_matrix

array([[1.0000002 , 0.60491216, 0.09593558, 0.20255241, 0.2823203 ,
        0.21441258, 0.30493483, 0.62655663, 0.23472585, 0.10024057],
       [0.60491216, 1.0000002 , 0.1717555 , 0.20117478, 0.25644535,
        0.30296105, 0.35528207, 0.79167366, 0.33665824, 0.20764989],
       [0.09593558, 0.1717555 , 1.        , 0.1501966 , 0.26319483,
        0.29961205, 0.48962337, 0.18523768, 0.34414434, 0.6893631 ],
       [0.20255241, 0.20117478, 0.1501966 , 1.0000001 , 0.16988723,
        0.16885036, 0.21340138, 0.29436833, 0.58422685, 0.14165233],
       [0.2823203 , 0.25644535, 0.26319483, 0.16988723, 0.9999998 ,
        0.40530014, 0.29446724, 0.27513355, 0.26107383, 0.253823  ],
       [0.21441258, 0.30296105, 0.29961205, 0.16885036, 0.40530014,
        1.0000001 , 0.38773024, 0.27713224, 0.35022694, 0.35668528],
       [0.30493483, 0.35528207, 0.48962337, 0.21340138, 0.29446724,
        0.38773024, 1.        , 0.44833386, 0.3759947 , 0.46243042],
       [0.62655663, 0.79167366, 0.18523768, 0.29436833, 0.27513355,
        0.27713224, 0.44833386, 0.99999994, 0.48205128, 0.20393208],
       [0.23472585, 0.33665824, 0.34414434, 0.58422685, 0.26107383,
        0.35022694, 0.3759947 , 0.48205128, 1.0000001 , 0.24013421],
       [0.10024057, 0.20764989, 0.6893631 , 0.14165233, 0.253823  ,
        0.35668528, 0.46243042, 0.20393208, 0.24013421, 1.        ]],
      dtype=float32)

In [52]:
similarity_matrix.shape

(10, 10)

In [53]:
similarity_df = pd.DataFrame(
    similarity_matrix, index=profiles_df["title"], columns=profiles_df["title"]
)

similarity_df

title,The Early Days of Stripe,Building SpaceX,AI for Healthcare,The Psychology of Habits,Cloud Computing Fundamentals,Modern Data Engineering,Machine Learning in Finance,Startup Fundraising Guide,Nutrition Science,Large Language Models
title,,,,,,,,,,
The Early Days of Stripe,1.000000,0.604912,0.095936,0.202552,0.282320,0.214413,0.304935,0.626557,0.234726,0.100241
Building SpaceX,0.604912,1.000000,0.171755,0.201175,0.256445,0.302961,0.355282,0.791674,0.336658,0.207650
AI for Healthcare,0.095936,0.171755,1.000000,0.150197,0.263195,0.299612,0.489623,0.185238,0.344144,0.689363
The Psychology of Habits,0.202552,0.201175,0.150197,1.000000,0.169887,0.168850,0.213401,0.294368,0.584227,0.141652
Cloud Computing Fundamentals,0.282320,0.256445,0.263195,0.169887,1.000000,0.405300,0.294467,0.275134,0.261074,0.253823
Modern Data Engineering,0.214413,0.302961,0.299612,0.168850,0.405300,1.000000,0.387730,0.277132,0.350227,0.356685
Machine Learning in Finance,0.304935,0.355282,0.489623,0.213401,0.294467,0.387730,1.000000,0.448334,0.375995,0.462430
Startup Fundraising Guide,0.626557,0.791674,0.185238,0.294368,0.275134,0.277132,0.448334,1.000000,0.482051,0.203932
Nutrition Science,0.234726,0.336658,0.344144,0.584227,0.261074,0.350227,0.375995,0.482051,1.000000,0.240134
Large Language Models,0.100241,0.207650,0.689363,0.141652,0.253823,0.356685,0.462430,0.203932,0.240134,1.000000

In [54]:
target_index = 0

scores = similarity_matrix[target_index]

scores

array([1.0000002 , 0.60491216, 0.09593558, 0.20255241, 0.2823203 ,
       0.21441258, 0.30493483, 0.62655663, 0.23472585, 0.10024057],
      dtype=float32)

In [55]:
ranked_idx = np.argsort(scores)[::-1]

In [56]:
for idx in ranked_idx[:5]:

    print()

    print(profiles_df.iloc[idx]["title"])

    print(round(scores[idx], 4))

The Early Days of Stripe
1.0

Startup Fundraising Guide
0.6266

Building SpaceX
0.6049

Machine Learning in Finance
0.3049

Cloud Computing Fundamentals
0.2823

In [57]:
embedding_metadata = profiles_df[["item_id", "title", "category"]]

In [58]:
embedding_metadata.head()

   item_id                         title                 category
0        1      The Early Days of Stripe                  Startup
1        2               Building SpaceX                  Startup
2        3             AI for Healthcare  Artificial Intelligence
3        4      The Psychology of Habits                 Wellness
4        5  Cloud Computing Fundamentals               Technology

In [59]:
embedding_metadata.head()

   item_id                         title                 category
0        1      The Early Days of Stripe                  Startup
1        2               Building SpaceX                  Startup
2        3             AI for Healthcare  Artificial Intelligence
3        4      The Psychology of Habits                 Wellness
4        5  Cloud Computing Fundamentals               Technology

In [60]:
np.save("../data/item_embeddings.npy", item_embeddings)

In [61]:
embedding_df.to_csv("../data/item_embeddings.csv", index=False)

In [62]:
embedding_metadata.to_csv("../data/item_embedding_metadata.csv", index=False)

In [63]:
loaded_embeddings = np.load("../data/item_embeddings.npy")

loaded_embeddings.shape

(10, 384)