In [1]:
# ==========================================
# Notebook 07
# User Profile Vector Engine
# ==========================================

import pandas as pd
import numpy as np

In [2]:
items_df = pd.read_csv("../data/items.csv")

profiles_df = pd.read_csv("../data/item_profiles.csv")

interactions_df = pd.read_csv("../data/user_interactions.csv")

item_embeddings = np.load("../data/item_embeddings.npy")

In [3]:
print("Items:", len(items_df))

print()

print("Users:", interactions_df["user_id"].nunique())

print()

print("Embeddings Shape:", item_embeddings.shape)

Items: 10

Users: 5

Embeddings Shape: (10, 384)

In [4]:
interactions_df.head()

   user_id  item_id  rating
0      101        1       5
1      101        2       5
2      101        5       4
3      102        1       5
4      102        8       5

In [5]:
interactions_df[interactions_df["user_id"] == 101]

   user_id  item_id  rating
0      101        1       5
1      101        2       5
2      101        5       4

In [6]:
interactions_df[interactions_df["user_id"] == 101]

   user_id  item_id  rating
0      101        1       5
1      101        2       5
2      101        5       4

In [7]:
item_index_mapping = dict(zip(profiles_df["item_id"], profiles_df.index))

item_index_mapping

{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9}

In [8]:
user_profiles = []

for user_id in interactions_df["user_id"].unique():

    user_history = interactions_df[interactions_df["user_id"] == user_id]

    consumed_items = user_history["item_id"].tolist()

    consumed_embeddings = []

    for item_id in consumed_items:

        embedding_index = item_index_mapping[item_id]

        consumed_embeddings.append(item_embeddings[embedding_index])

    user_vector = np.mean(consumed_embeddings, axis=0)

    user_profiles.append({"user_id": user_id, "user_vector": user_vector})

In [9]:
len(user_profiles)

5

In [11]:
user_profiles

[{'user_id': 101,
  'user_vector': array([ 8.21680669e-03, -5.54117747e-03, -3.33765969e-02, -5.51803894e-02,
          1.49221160e-03, -3.07114329e-02,  3.97837199e-02,  2.70672385e-02,
         -3.90812904e-02,  5.19380579e-03, -2.84225568e-02,  1.56204440e-02,
          6.78217551e-03,  1.65611450e-02, -4.06162255e-02, -1.55382594e-02,
          1.55002857e-02, -5.71679473e-02, -1.22728469e-02,  2.30693202e-02,
         -2.65736431e-02, -4.54670079e-02, -1.17608309e-02,  4.17895876e-02,
          6.14151098e-02,  8.00634325e-02, -1.68158617e-02, -8.97147413e-03,
         -6.01649396e-02, -4.81769443e-02, -4.27343510e-03,  5.13095073e-02,
          2.62768548e-02,  3.71304154e-02,  3.33361663e-02,  2.95535326e-02,
          1.57578271e-02, -3.32237072e-02, -1.07257562e-02, -2.09950581e-02,
          6.45974502e-02, -4.30020094e-02, -5.15961349e-02,  2.45764907e-02,
          1.81658026e-02, -3.39043699e-02, -2.33578514e-02, -3.63786854e-02,
         -5.33905625e-03,  1.91127304e-02, -9.94228106e-03, -1.35641322e-01,
          2.60124858e-02,  2.04310268e-02, -2.64826175e-02,  1.02901356e-02,
         -1.10752815e-02, -5.68392090e-02,  4.91451286e-02, -5.94426803e-02,
          3.74600254e-02, -2.60060858e-02,  5.76568283e-02,  7.94643462e-02,
          4.74922499e-03,  3.60203423e-02, -1.80880781e-02,  4.67308201e-02,
         -3.09257749e-02, -2.11971370e-03,  3.26530077e-02,  1.73760147e-03,
         -3.79024856e-02,  6.42753839e-02, -1.60190780e-02, -1.99608635e-02,
          4.34755944e-02,  7.24514201e-02,  4.59880941e-02, -2.80623212e-02,
         -3.93857509e-02,  9.98341013e-03, -8.25853944e-02,  2.16161665e-02,
         -9.17818248e-02,  1.20396754e-02,  4.06586612e-03, -3.05082370e-02,
          8.67684651e-03, -3.91072333e-02, -3.40034105e-02,  4.77087758e-02,
          4.59379703e-02, -7.26132328e-03, -4.96366434e-02, -6.39358833e-02,
         -7.60292262e-02, -7.59809539e-02, -3.64365033e-03,  5.96277788e-03,
          2.95743700e-02,  2.96801943e-02,  3.49091254e-02,  3.43476236e-02,
          8.81441310e-03,  5.72986715e-03, -2.81280070e-03,  5.62071390e-02,
          5.24416380e-02, -5.57365529e-02, -3.34168226e-02,  1.14140594e-02,
         -1.54973716e-02, -1.16371633e-02,  5.37030399e-04,  1.51951434e-02,
         -4.49691303e-02,  1.16532743e-02,  9.25085843e-02,  5.03257066e-02,
          1.71336476e-02,  6.20110566e-03, -2.79106107e-02, -1.34877712e-01,
         -7.05902502e-02, -6.11708791e-04, -5.10021411e-02, -1.57387875e-33,
         -2.42535099e-02,  1.71338134e-02,  2.23676097e-02,  4.12147678e-02,
          3.33170034e-02, -3.01611051e-02, -3.08603514e-02,  2.08108947e-02,
         -1.06894493e-01,  9.88898217e-04, -5.96242025e-05,  2.16071662e-02,
         -2.43632216e-02,  7.33818188e-02,  4.10414450e-02, -5.24337180e-02,
          2.71229874e-02,  1.72827952e-02,  2.91179735e-02, -1.18978871e-02,
          1.16731355e-03, -1.98511612e-02, -2.22537504e-03, -1.60280894e-02,
          4.27008718e-02, -6.51539266e-02, -4.23378944e-02, -2.46221498e-02,
          5.88367991e-02,  5.01631387e-02, -3.93641507e-03,  2.37043258e-02,
          2.56911758e-02, -3.32475118e-02, -2.86556482e-02,  2.13360991e-02,
          2.82392856e-02, -6.46693632e-02,  7.74614280e-03, -8.47510155e-03,
         -2.00917628e-02, -1.46045899e-02, -4.09596749e-02, -7.89346769e-02,
          3.48096224e-03,  4.87542637e-02,  5.37064485e-02, -8.59515276e-03,
          1.03196211e-01,  1.96309481e-02, -3.10759563e-02, -1.01851299e-04,
          4.97143865e-02, -1.97480991e-02,  2.09522974e-02,  6.59863884e-03,
         -3.11953425e-02, -2.50160825e-02, -5.64479716e-02,  5.64887375e-03,
         -9.26733389e-02, -4.47082035e-02, -3.66211645e-02,  2.91306060e-02,
         -2.23231111e-02, -3.14539261e-02,  1.07065700e-01,  3.58348303e-02,
         -4.75460244e-03,  2.72335391e-02, -8.12496524e-03, -6.36818632e-03,
         -1.75059587e-02,  4.96472567e-02,  2.26607379e-02, -9.16336104e-03,
         -6.63068071e-02, -1.40600221e-03, -3.01348343e-02,  7.28833452e-02,
         -7.02200085e-02, -3.95216756e-02, -3.67172621e-02,  1.12219779e-02,
         -9.17997956e-03,  1.50745632e-02,  8.73946771e-02, -5.17281406e-02,
         -2.51202155e-02,  5.06642275e-02, -7.11290017e-02,  1.78365165e-03,
          1.14520798e-02,  4.25083898e-02, -3.98712121e-02, -1.80821392e-33,
          2.49910355e-02, -2.88643986e-02, -1.75089613e-02,  2.05514226e-02,
          5.86218350e-02, -1.71031877e-02,  3.32052517e-03,  2.10634768e-02,
         -3.65050137e-02,  5.59179783e-02, -4.66895364e-02,  2.61552632e-02,
         -5.99570461e-02, -3.55192140e-04, -1.51178269e-02, -3.74521948e-02,
         -1.74910983e-03, -1.92680489e-02,  3.38123105e-02,  1.37835825e-02,
          4.59234230e-02, -2.34241318e-02, -2.76933666e-02,  4.62637991e-02,
          5.18061332e-02,  3.33260149e-02,  7.06646079e-03,  4.52478863e-02,
         -1.18504716e-02,  3.12988966e-04, -4.55288440e-02,  2.04674471e-02,
         -8.15677166e-04,  2.69719902e-02, -7.68890092e-03, -5.37290424e-03,
          1.57701764e-02, -2.07249820e-02,  1.33632096e-02, -1.64496582e-02,
         -1.01558892e-02, -3.38985659e-02, -1.79664101e-02, -5.93295433e-02,
         -3.37494947e-02, -6.53610975e-02,  2.03465987e-02,  4.08441350e-02,
         -2.82784477e-02, -5.53972041e-03, -9.96947754e-03,  2.86734905e-02,
          1.10471668e-02,  2.17836443e-02, -2.71069054e-02,  1.66339073e-02,
          1.11634163e-02,  5.56743033e-02, -6.55967891e-02,  3.39325890e-02,
          1.88042764e-02, -1.23298466e-02,  5.20880856e-02,  5.94565012e-02,
         -1.71228629e-02, -7.54320398e-02,  1.68044716e-02,  1.93159189e-02,
         -9.88689736e-02, -3.21332291e-02,  1.91950966e-02,  6.83671283e-03,
         -4.05014344e-02,  1.95495412e-02, -9.73552167e-02, -4.01991680e-02,
         -1.70229038e-03, -6.43480942e-02,  4.44523245e-03, -1.37567893e-02,
          5.24886362e-02,  2.32947767e-02, -9.22109466e-03,  7.93214366e-02,
          3.82368863e-02, -7.38286274e-03,  6.56845942e-02, -5.86342672e-03,
         -2.41995440e-03,  4.86132456e-03, -6.04576282e-02, -6.36453256e-02,
         -4.29106504e-02,  6.06705509e-02, -8.27088058e-02, -2.68365081e-08,
         -5.83591349e-02,  2.49101669e-02, -5.03565483e-02,  4.17267531e-02,
         -6.27686083e-03,  4.18232493e-02,  2.21501440e-02, -2.49321386e-02,
         -1.33660762e-02,  2.72619352e-02, -1.27985990e-02,  5.70792938e-03,
         -1.67765040e-02,  4.63604964e-02,  2.86283344e-02, -1.76291410e-02,
         -2.01358888e-02,  1.58060398e-02, -4.87985834e-03,  1.24930069e-02,
          1.72988176e-02,  7.15768561e-02, -2.54144724e-02, -4.80890572e-02,
          1.22697903e-02, -4.31247288e-03,  9.16120317e-03,  3.44178416e-02,
          2.81823408e-02,  9.58677940e-03,  1.81825962e-02,  2.75229532e-02,
         -2.42345426e-02, -1.31650316e-03,  3.98186110e-02,  1.65972710e-02,
         -1.13433925e-02, -1.97165157e-03,  1.93983261e-02, -7.30038015e-03,
          1.70843920e-03, -1.60706881e-03,  4.46320474e-02, -2.52995882e-02,
         -5.23224957e-02, -1.74418371e-02, -5.22046983e-02,  8.28399137e-02,
         -1.35977482e-02, -3.76315117e-02,  6.33597607e-03, -1.86981130e-02,
         -3.97511460e-02,  4.67070341e-02,  2.18381118e-02, -2.42975610e-03,
         -4.75587649e-03,  2.60054115e-02,  3.87431569e-02,  3.11307069e-02,
          8.43495429e-02, -1.73897464e-02,  3.79952006e-02,  2.31914353e-02],
        dtype=float32)},
 {'user_id': 102,
  'user_vector': array([ 1.68620069e-02, -2.76161879e-02, -2.36330628e-02, -4.96619530e-02,
          1.21526653e-02, -1.80814881e-02,  3.95058244e-02,  2.44674962e-02,
         -4.70999181e-02, -2.19209362e-02, -1.45471795e-02,  1.90675294e-03,
         -8.13896209e-03,  2.28219032e-02, -4.22892272e-02, -9.67967231e-03,
         -2.27844226e-03, -5.10107726e-02,  3.19980308e-02,  4.25601192e-02,
         -2.54666340e-02, -5.81928194e-02,  2.27635521e-02,  3.50623280e-02,
          8.47486630e-02,  5.11335284e-02,  1.57010425e-02,  2.65040454e-02,
         -5.28815091e-02, -4.70268540e-02,  1.03072179e-02,  4.29004319e-02,
          3.79376598e-02,  2.13970114e-02,  5.82304411e-02,  3.34470682e-02,
         -9.53573827e-03, -1.08538975e-03, -2.52663698e-02, -1.76466852e-02,
          5.26916385e-02, -4.91766036e-02, -4.13599201e-02,  3.64651121e-02,
          2.95967385e-02, -5.55271395e-02, -2.19651535e-02, -3.64030711e-02,
          1.03095146e-02,  4.24760878e-02, -7.00566731e-03, -1.38878092e-01,
          4.86588180e-02, -1.56100979e-02, -8.79653916e-03,  3.87599505e-02,
         -4.43067066e-02, -7.83022046e-02,  5.04829325e-02, -6.01783246e-02,
          5.10641038e-02,  8.06051772e-03,  5.22950478e-02,  6.61256462e-02,
          3.22995242e-03,  1.98422652e-02, -2.39450689e-02,  9.57400724e-02,
         -2.70290170e-02, -6.10558549e-03,  6.36341795e-02, -8.80357344e-03,
         -1.87390670e-02,  5.67158051e-02, -1.81603152e-02, -1.40883289e-02,
          3.99817489e-02,  9.53552201e-02,  7.15930387e-02, -5.00655510e-02,
         -5.13512790e-02, -1.65650435e-02, -8.15217718e-02,  2.30732616e-02,
         -1.29069850e-01,  5.25279492e-02,  1.80742461e-02, -2.00969074e-02,
          2.17148289e-02,  1.06188348e-02, -7.25070313e-02,  4.59633060e-02,
          5.82413040e-02, -2.05480959e-02, -6.08278811e-02, -3.10634375e-02,
         -8.39793906e-02, -9.46796760e-02, -4.90134023e-03,  8.87151435e-03,
          3.04760505e-02,  5.13187237e-03,  3.09898052e-02,  4.31546755e-02,
          8.29937577e-04, -1.02992179e-02,  4.36818600e-03,  5.12971096e-02,
          7.06527159e-02, -2.51055881e-02, -1.46799348e-02,  1.71478167e-02,
         -6.95906533e-03, -1.40054598e-02, -8.27155542e-03,  1.60420965e-02,
         -6.04386330e-02,  1.40729100e-02,  1.01834632e-01,  7.08311200e-02,
          2.59525552e-02,  3.73649709e-02, -4.23016846e-02, -1.44255593e-01,
         -8.85982215e-02, -2.60530207e-02, -8.23618844e-02, -1.12385121e-33,
         -4.70571546e-03,  3.01543605e-02,  3.99225205e-02,  6.66039363e-02,
         -1.74919458e-03, -2.98292413e-02, -2.97685061e-02,  2.39842534e-02,
         -1.13389336e-01,  2.46260110e-02,  1.94442775e-02, -1.22422986e-02,
         -2.98178345e-02,  8.95609930e-02,  1.55813992e-03, -6.46512583e-02,
          3.37562114e-02, -3.48491711e-03, -1.02978572e-02, -2.23498512e-02,
         -1.70026291e-02, -2.36159028e-03, -1.13473237e-02, -1.39297992e-02,
          4.30494957e-02, -7.87890628e-02, -5.52729666e-02, -6.56563556e-03,
          3.65126729e-02,  5.86870611e-02,  2.60442751e-03,  7.12762354e-03,
          1.54919541e-02, -4.48119640e-02, -3.17684226e-02,  2.16709003e-02,
          5.77669851e-02, -7.25364536e-02, -1.29320072e-02, -2.46586706e-02,
         -3.18000019e-02, -1.11103663e-02, -2.80792732e-02, -7.04650506e-02,
          5.37026674e-04,  5.72301149e-02,  4.40514497e-02, -1.83421168e-02,
          1.35430634e-01,  1.50573058e-02, -5.27313352e-02, -1.48833804e-02,
          2.36677080e-02, -3.39465104e-02, -4.46805218e-03, -1.93564165e-02,
         -7.10941628e-02, -3.29291411e-02, -7.83126131e-02, -4.44873162e-02,
         -7.30280578e-02, -2.82532945e-02, -3.92561406e-02,  6.37409911e-02,
         -4.46152054e-02, -3.66752944e-03,  1.23117916e-01,  4.54521589e-02,
         -5.77808684e-03,  3.27421837e-02, -1.60370171e-02,  2.79111019e-03,
         -3.69661339e-02,  5.01222312e-02,  3.01627517e-02,  1.85569450e-02,
         -6.58863634e-02,  3.23308050e-03, -7.12322071e-03,  9.99177173e-02,
         -2.22864058e-02, -7.15259984e-02, -3.80980410e-02,  3.02220490e-02,
         -1.39359944e-03,  6.63372353e-02,  1.14588968e-01, -6.14651181e-02,
          4.80399886e-03,  4.15813848e-02, -6.32574484e-02,  2.75005698e-02,
         -1.68606956e-02,  6.09619133e-02, -5.24172932e-02, -1.93101928e-33,
          5.69085181e-02, -1.09873563e-02,  3.35121714e-02, -3.59752439e-02,
          4.93189730e-02,  5.50297834e-03,  2.75484622e-02,  4.32816613e-03,
         -1.67727824e-02,  5.19597717e-02, -4.81929593e-02,  3.72721441e-02,
         -7.28039816e-02,  2.00222642e-03, -1.08264200e-02, -4.84647602e-02,
          3.52285034e-03,  1.89249143e-02,  4.71538492e-02,  1.47975311e-02,
          5.18371873e-02, -2.50609498e-02, -5.74958622e-02,  4.42487784e-02,
          3.39855291e-02,  1.96226854e-02,  2.42260862e-02,  1.01532400e-01,
         -6.43129870e-02,  1.96852814e-02, -2.79359594e-02,  4.65388186e-02,
         -2.32764822e-03,  2.09058356e-02, -3.92326154e-02,  6.72295829e-03,
          8.60385317e-03, -6.97638616e-02,  2.08357964e-02, -4.20591086e-02,
         -1.30082620e-02, -1.97638422e-02,  3.46502289e-03, -4.00420390e-02,
         -6.58883601e-02, -8.40351880e-02,  4.47359867e-02,  5.51672513e-03,
         -9.04423278e-03,  1.27830857e-03, -3.11453622e-02,  1.21694384e-02,
         -3.04230140e-03,  1.84898749e-02, -5.29769212e-02,  2.49705184e-02,
          1.02885617e-02,  5.94067276e-02, -4.19388227e-02,  3.52048762e-02,
          1.02436868e-02,  4.97871451e-02,  4.51863371e-02,  6.19009994e-02,
         -4.30576801e-02, -1.04107350e-01,  2.14359965e-02,  3.47247012e-02,
         -1.15858436e-01, -5.41708805e-02,  1.73461568e-02,  2.90648150e-03,
         -3.26557793e-02,  2.98444629e-02, -1.07936405e-01, -2.13599745e-02,
          7.21536716e-03, -6.46523088e-02, -1.31536527e-02, -3.06911338e-02,
          7.98343644e-02, -8.82156938e-03, -8.11564643e-03,  9.08699334e-02,
          3.17721963e-02, -5.31079888e-04,  4.31578606e-02, -1.07023520e-02,
          1.03681581e-02,  2.31362674e-02, -5.11472933e-02, -9.58753228e-02,
          1.11167632e-04,  8.02805051e-02, -7.10893273e-02, -2.79365882e-08,
         -5.30109964e-02,  2.16026902e-02, -3.72106694e-02,  4.34880853e-02,
          1.37410788e-02,  1.57008190e-02, -5.04222326e-03, -1.98530145e-02,
          1.17492676e-02,  9.24224313e-03, -3.33663300e-02,  4.21563573e-02,
         -6.09090067e-02,  5.23397438e-02, -9.97424591e-03, -2.69642547e-02,
         -1.41716758e-02,  3.97568457e-02, -5.61157847e-03,  7.18763843e-03,
         -1.42700821e-02,  7.16494173e-02, -2.51956750e-02, -5.73939569e-02,
          3.13971494e-03, -1.44682378e-02, -1.78297479e-02,  2.86831614e-02,
          5.30357659e-02, -1.90454908e-03,  3.68189998e-02,  4.23999093e-02,
         -1.86546575e-02, -1.78576894e-02,  5.33044012e-03,  4.20221724e-02,
         -1.63359493e-02, -1.44036086e-02, -4.70458763e-03, -6.78796461e-03,
          1.75999291e-02, -4.70412849e-03,  4.68967222e-02, -5.18547297e-02,
         -9.92179587e-02,  3.33299045e-03, -7.22722784e-02,  6.01365380e-02,
          2.27934625e-02, -9.81029347e-02,  8.52454361e-03, -2.28344966e-02,
         -2.23065969e-02,  8.47567990e-03,  2.77395640e-02,  2.12602317e-02,
         -3.18222982e-03,  6.07879646e-02,  1.69701371e-02, -1.35083674e-02,
          1.04433484e-01, -3.41642201e-02,  4.35546823e-02,  1.00987719e-03],
        dtype=float32)},
 {'user_id': 103,
  'user_vector': array([ 3.83649394e-02,  9.71691217e-03, -3.76633853e-02,  5.67942113e-02,
         -2.44903229e-02, -3.59804183e-02,  1.74170509e-02, -9.72493319e-04,
         -9.69938338e-02, -4.46938463e-02,  1.43015012e-02, -1.80623215e-03,
         -3.07574775e-02, -6.23522811e-02,  5.98092228e-02, -1.14864940e-02,
          3.45690735e-02,  2.24394836e-02, -3.20661291e-02,  4.29748893e-02,
          1.25531666e-02,  4.11636643e-02,  7.52606690e-02,  1.10688522e-01,
          1.96472043e-03,  2.31318735e-02, -2.45898273e-02, -4.32835221e-02,
         -6.78646863e-02, -1.64957829e-02,  5.71809784e-02,  7.07063377e-02,
          7.36321956e-02,  8.09430983e-03, -1.24010369e-02, -2.17521526e-02,
         -3.78262326e-02,  1.73115693e-02, -2.98756957e-02,  1.21355196e-02,
         -3.72615568e-02, -5.25306761e-02, -3.37010436e-02,  1.26629714e-02,
         -3.41670066e-02, -2.78685968e-02, -2.89327502e-02, -7.44160116e-02,
          7.91292079e-03,  3.11487596e-02, -5.10547236e-02, -5.46839722e-02,
          1.12191145e-03,  1.21803293e-02,  7.07463324e-02,  4.11889330e-02,
         -1.93759762e-02, -7.52120167e-02, -5.68716265e-02,  8.08244199e-02,
          6.13083765e-02, -2.83840988e-02,  1.88604426e-02,  9.03068781e-02,
          3.75644974e-02,  4.53504696e-02, -4.32145521e-02,  7.60741979e-02,
         -4.36599851e-02, -2.68913191e-02, -2.61269361e-02, -1.18222814e-02,
          3.42839025e-02, -1.96274985e-02,  1.00832075e-01, -1.94618441e-02,
         -8.21708608e-03, -1.43456757e-02,  4.65307273e-02, -5.62200248e-02,
         -2.88816988e-02,  7.69921094e-02,  3.32425758e-02,  1.83375478e-02,
          2.68128561e-03, -2.51925476e-02,  4.48113587e-03,  3.62859890e-02,
         -4.52999473e-02, -2.79894862e-02, -5.26243374e-02,  1.88385043e-03,
          5.56784868e-03,  1.82222947e-03, -8.19730535e-02, -6.36216579e-03,
         -3.77922505e-02, -9.93997082e-02, -1.85288908e-03, -9.75028239e-03,
          2.42529064e-03,  2.63113324e-02, -2.86139660e-02,  3.22825909e-02,
         -4.37922664e-02, -2.54922695e-02, -3.01284045e-02,  1.15812898e-01,
          3.86355557e-02,  3.99790425e-03,  3.85060310e-02,  4.66927327e-02,
         -3.80211920e-02, -1.50075536e-02,  8.87030177e-03,  6.22459613e-02,
          2.02948991e-02,  4.08162177e-03,  9.56200063e-02,  6.46606013e-02,
          2.48747878e-03, -2.66624801e-02,  6.76672608e-02, -1.24961220e-01,
         -7.43696690e-02, -4.22460064e-02, -2.20112205e-02, -3.48938004e-33,
         -2.01325137e-02,  1.44508518e-02,  8.77048522e-02,  3.29805613e-02,
         -5.69828786e-04, -2.39660647e-02, -5.67588732e-02, -1.08205238e-02,
          1.58639345e-02, -2.56075729e-02,  1.09783605e-01,  2.25269422e-02,
         -5.48674390e-02,  8.31411183e-02,  1.42850224e-02, -6.41200468e-02,
         -1.91004965e-02,  7.19528198e-02, -2.03026049e-02,  2.07732804e-02,
         -3.20533384e-03, -5.11416271e-02,  1.82353742e-02,  8.58067442e-03,
          7.71592604e-03, -1.02477968e-02, -2.61976421e-02, -3.37181753e-03,
         -7.41387531e-03,  2.77611725e-02,  4.88920622e-02,  3.34213972e-02,
         -2.29185447e-02, -9.93122756e-02, -1.01836082e-02, -5.62530085e-02,
          3.31225023e-02,  4.52252757e-03, -4.13388684e-02, -5.58763817e-02,
         -5.67046106e-02, -2.87999790e-02,  1.27955154e-02, -7.53015513e-03,
          3.41324508e-02,  1.02501623e-02,  4.67817709e-02,  3.43229575e-03,
          6.57034218e-02,  1.55071169e-02, -2.49393489e-02, -4.06544358e-02,
          5.65565005e-02, -1.05810158e-01, -6.37837648e-02, -4.10473123e-02,
         -4.92994767e-03,  8.51589721e-05, -8.17583129e-02,  1.34694315e-02,
         -3.18852738e-02,  3.73132750e-02, -1.90322772e-02, -8.64428207e-02,
         -3.34948767e-03, -4.47687507e-03,  4.91666198e-02,  3.32304044e-03,
         -2.46186834e-02,  5.17182164e-02,  4.41180393e-02,  4.67999279e-02,
         -5.76814935e-02,  2.87212264e-02,  9.89877731e-02,  1.09502254e-02,
         -6.26574978e-02, -5.92698380e-02, -7.42989406e-02,  4.76445220e-02,
          6.30521122e-03, -2.97943875e-02, -5.22468798e-02,  1.82512403e-03,
         -1.77484266e-02,  6.05697706e-02, -8.75807554e-03, -1.91332139e-02,
          6.74972907e-02,  2.22467948e-02,  4.30870149e-03,  6.05355762e-02,
         -6.52156072e-03,  9.30599123e-02, -6.68976158e-02, -1.68943793e-34,
          3.61167900e-02,  7.23850122e-03, -7.17484951e-02,  4.38689888e-02,
          8.85347128e-02, -5.29526547e-02, -2.13115923e-02,  5.00310957e-02,
         -4.31045368e-02,  4.87536788e-02, -3.36025432e-02, -2.11718008e-02,
         -1.20267197e-01, -5.40465675e-03,  1.74441729e-02,  1.19398311e-02,
         -4.18305770e-02,  8.69051740e-03, -5.64249493e-02,  7.14850500e-02,
          3.71109252e-03,  4.18065339e-02, -2.95574106e-02,  8.94157775e-03,
          1.21468119e-02,  7.10446835e-02,  7.39256106e-03,  7.89024159e-02,
          5.61597571e-02, -4.82867844e-02, -2.91358996e-02, -7.44136609e-03,
         -1.58024561e-02, -7.10685700e-02,  3.16628776e-02, -3.34072784e-02,

In [12]:
user_profile_df = pd.DataFrame(
    {
        "user_id": [profile["user_id"] for profile in user_profiles],
        "user_vector": [profile["user_vector"] for profile in user_profiles],
    }
)

In [13]:
user_profile_df

   user_id                                        user_vector
0      101  [0.008216807, -0.0055411775, -0.033376597, -0....
1      102  [0.016862007, -0.027616188, -0.023633063, -0.0...
2      103  [0.03836494, 0.009716912, -0.037663385, 0.0567...
3      104  [-0.06547663, -0.018401783, -0.004169222, -0.0...
4      105  [-0.02725611, 0.019708049, -0.055300195, -0.01...

In [14]:
user_embedding_matrix = np.vstack(user_profile_df["user_vector"])

user_embedding_matrix.shape

(5, 384)

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
user_similarity_matrix = cosine_similarity(user_embedding_matrix)

user_similarity_matrix

array([[1.0000001 , 0.89157   , 0.34353018, 0.3552066 , 0.6530695 ],
       [0.89157   , 0.99999976, 0.37069267, 0.31160516, 0.4499327 ],
       [0.34353018, 0.37069267, 0.99999994, 0.32846677, 0.3801741 ],
       [0.3552066 , 0.31160516, 0.32846677, 1.0000001 , 0.6677512 ],
       [0.6530695 , 0.4499327 , 0.3801741 , 0.6677512 , 1.0000002 ]],
      dtype=float32)

In [17]:
user_similarity_df = pd.DataFrame(
    user_similarity_matrix,
    index=user_profile_df["user_id"],
    columns=user_profile_df["user_id"],
)

user_similarity_df

user_id       101       102       103       104       105
user_id
101      1.000000  0.891570  0.343530  0.355207  0.653069
102      0.891570  1.000000  0.370693  0.311605  0.449933
103      0.343530  0.370693  1.000000  0.328467  0.380174
104      0.355207  0.311605  0.328467  1.000000  0.667751
105      0.653069  0.449933  0.380174  0.667751  1.000000

In [18]:
target_user = 101

user_idx = user_profile_df[user_profile_df["user_id"] == target_user].index[0]

scores = user_similarity_matrix[user_idx]

scores

array([1.0000001 , 0.89157   , 0.34353018, 0.3552066 , 0.6530695 ],
      dtype=float32)

In [19]:
ranked_idx = np.argsort(scores)[::-1]

ranked_idx

array([0, 1, 4, 3, 2], dtype=int64)

In [20]:
for idx in ranked_idx:

    print()

    print(user_profile_df.iloc[idx]["user_id"])

    print(round(scores[idx], 4))

101
1.0

102
0.8916

105
0.6531

104
0.3552

103
0.3435

In [21]:
alpha = 0.8

In [22]:
current_profile = user_profiles[0]["user_vector"]

In [23]:
latest_item_embedding = item_embeddings[9]

In [24]:
updated_profile = alpha * current_profile + (1 - alpha) * latest_item_embedding

In [25]:
updated_profile.shape

(384,)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
profile_shift = cosine_similarity(
    current_profile.reshape(1, -1), updated_profile.reshape(1, -1)
)[0][0]

profile_shift

0.9596695

In [28]:
user_embedding_df = pd.DataFrame(user_embedding_matrix)

In [29]:
user_embedding_df.insert(0, "user_id", user_profile_df["user_id"])

In [30]:
user_embedding_df.head()

,user_id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
0,101,0.008217,-0.005541,-0.033377,-0.055180,0.001492,-0.030711,0.039784,0.027067,-0.039081,...,0.021838,-0.002430,-0.004756,0.026005,0.038743,0.031131,0.084350,-0.017390,0.037995,0.023191
1,102,0.016862,-0.027616,-0.023633,-0.049662,0.012153,-0.018081,0.039506,0.024467,-0.047100,...,0.027740,0.021260,-0.003182,0.060788,0.016970,-0.013508,0.104433,-0.034164,0.043555,0.001010
2,103,0.038365,0.009717,-0.037663,0.056794,-0.024490,-0.035980,0.017417,-0.000972,-0.096994,...,-0.037571,0.039922,0.047643,0.004742,-0.030438,-0.039578,0.142901,0.026361,-0.001394,-0.013149
3,104,-0.065477,-0.018402,-0.004169,-0.012562,0.032085,-0.035960,-0.010831,0.031132,-0.045164,...,0.049698,0.037003,0.035458,-0.063650,-0.009495,0.040789,0.053854,0.040240,-0.029143,0.004683
4,105,-0.027256,0.019708,-0.055300,-0.013605,0.013021,-0.079306,0.001470,0.003982,-0.042966,...,0.047351,0.006740,0.006698,-0.040654,0.053702,0.031907,0.073550,0.028771,0.013899,0.029564

In [31]:
np.save("../data/user_embeddings.npy", user_embedding_matrix)

In [32]:
user_embedding_df.to_csv("../data/user_profiles.csv", index=False)

In [33]:
loaded_profiles = pd.read_csv("../data/user_profiles.csv")

loaded_profiles.head()

,user_id,0,1,2,3,4,5,6,7,8,...,374,375,376,377,378,379,380,381,382,383
0,101,0.008217,-0.005541,-0.033377,-0.055180,0.001492,-0.030711,0.039784,0.027067,-0.039081,...,0.021838,-0.002430,-0.004756,0.026005,0.038743,0.031131,0.084350,-0.017390,0.037995,0.023191
1,102,0.016862,-0.027616,-0.023633,-0.049662,0.012153,-0.018081,0.039506,0.024467,-0.047100,...,0.027740,0.021260,-0.003182,0.060788,0.016970,-0.013508,0.104433,-0.034164,0.043555,0.001010
2,103,0.038365,0.009717,-0.037663,0.056794,-0.024490,-0.035980,0.017417,-0.000972,-0.096994,...,-0.037571,0.039922,0.047643,0.004742,-0.030438,-0.039578,0.142901,0.026361,-0.001394,-0.013149
3,104,-0.065477,-0.018402,-0.004169,-0.012562,0.032085,-0.035960,-0.010831,0.031132,-0.045164,...,0.049698,0.037003,0.035458,-0.063650,-0.009495,0.040789,0.053854,0.040240,-0.029143,0.004683
4,105,-0.027256,0.019708,-0.055300,-0.013605,0.013021,-0.079306,0.001470,0.003982,-0.042966,...,0.047351,0.006740,0.006698,-0.040654,0.053702,0.031907,0.073550,0.028771,0.013899,0.029564